# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellknown',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
