name: django tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django:
        - ''
        - '==2.2.13'

    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django${{ matrix.django }}
    - name: run tests
      run: ./manage.py test
